# Basic
title: Dove
subtitle: A blog-orientation theme for Dove
welcome_message: <a href="https://github.com/fe7s" target="_blank">Download the theme</a>
description: Dove is a iOS developer.
creator: <a href="https://fe7s.github.io/">@Dove</a>

url: "https://fe7s.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://fe7s.github.io/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: Dove
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: http://project.onevcat.com
    # gplus: 107108267983477358170
    mail: dove.io@outlook.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
